In [0]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    return str_text

In [2]:
read_file('wonderland.txt')

'Alice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do: once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, \'and what is the use of a book,\' thought Alice \'without pictures or\nconversations?\'\nSo she was considering in her own mind (as well as she could, for the\nhot day made her feel very sleepy and stupid), whether the pleasure\nof making a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a White Rabbit with pink eyes ran\nclose by her.\nThere was nothing so VERY remarkable in that; nor did Alice think it so\nVERY much out of the way to hear the Rabbit say to itself, \'Oh dear!\nOh dear! I shall be late!\' (when she thought it over afterwards, it\noccurred to her that she ought to have wondered at this, but at the time\nit all seemed quite natural); but when the Rabbit actually TOOK A WATCH\nOUT OF ITS WAISTCOAT-POCKET, an

In [0]:
import spacy
import string
from string import punctuation
nlp = spacy.load('en_core_web_sm',disable=['parser', 'tagger','ner'])

nlp.max_length = 1000000

In [0]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*\n  +,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [0]:
raw_text = read_file('wonderland.txt')
raw_text = [s for s in raw_text if s not in string.punctuation]
raw_text = "".join(raw_text)
tokens = separate_punc(raw_text)

In [6]:
len(tokens)

26931

In [0]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [8]:
' '.join(text_sequences[0])

'alice was beginning to get very tired of sitting by her sister on the bank and of having nothing to do once or twice she had'

In [9]:
' '.join(text_sequences[1])

'was beginning to get very tired of sitting by her sister on the bank and of having nothing to do once or twice she had peeped'

In [10]:
len(text_sequences)

26905

In [11]:
from keras.preprocessing.text import Tokenizer

Using TensorFlow backend.


In [0]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [13]:
sequences[0]

[11,
 12,
 298,
 3,
 102,
 29,
 515,
 7,
 375,
 79,
 16,
 457,
 19,
 1,
 1454,
 2,
 7,
 374,
 134,
 3,
 31,
 141,
 59,
 672,
 5,
 20]

In [14]:
tokenizer.index_word

{1: 'the',
 2: 'and',
 3: 'to',
 4: 'a',
 5: 'she',
 6: 'it',
 7: 'of',
 8: 'i',
 9: 'said',
 10: 'you',
 11: 'alice',
 12: 'was',
 13: 'in',
 14: 'that',
 15: 'as',
 16: 'her',
 17: 'nt',
 18: 'at',
 19: 'on',
 20: 'had',
 21: 'with',
 22: 'all',
 23: 'but',
 24: 'for',
 25: 'so',
 26: 'they',
 27: 'be',
 28: 'not',
 29: 'very',
 30: 'what',
 31: 'do',
 32: 'this',
 33: 'little',
 34: 'he',
 35: 'out',
 36: 'its',
 37: 'is',
 38: 'one',
 39: 'down',
 40: 'there',
 41: 'up',
 42: 'would',
 43: 'his',
 44: 'about',
 45: 'if',
 46: 'then',
 47: 'have',
 48: 'were',
 49: 'no',
 50: 'could',
 51: 'like',
 52: 'know',
 53: 'them',
 54: 'went',
 55: 'herself',
 56: 'again',
 57: 'when',
 58: 'did',
 59: 'or',
 60: 'thought',
 61: 'off',
 62: 's',
 63: 'time',
 64: 'me',
 65: 'queen',
 66: 'into',
 67: 'see',
 68: 'how',
 69: 'your',
 70: 'who',
 71: 'king',
 72: 'well',
 73: 'm',
 74: 'began',
 75: 'my',
 76: 'an',
 77: 'now',
 78: 'turtle',
 79: 'by',
 80: 'quite',
 81: 'hatter',
 82: 'mock

In [15]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

11 : alice
12 : was
298 : beginning
3 : to
102 : get
29 : very
515 : tired
7 : of
375 : sitting
79 : by
16 : her
457 : sister
19 : on
1 : the
1454 : bank
2 : and
7 : of
374 : having
134 : nothing
3 : to
31 : do
141 : once
59 : or
672 : twice
5 : she
20 : had


In [16]:
tokenizer.word_counts

OrderedDict([('alice', 9985),
             ('was', 9544),
             ('beginning', 315),
             ('to', 18718),
             ('get', 1175),
             ('very', 3724),
             ('tired', 163),
             ('of', 13155),
             ('sitting', 243),
             ('by', 1440),
             ('her', 6417),
             ('sister', 194),
             ('on', 5005),
             ('the', 42141),
             ('bank', 41),
             ('and', 21857),
             ('having', 252),
             ('nothing', 877),
             ('do', 3635),
             ('once', 828),
             ('or', 1973),
             ('twice', 128),
             ('she', 14117),
             ('had', 4836),
             ('peeped', 78),
             ('into', 1742),
             ('book', 182),
             ('reading', 78),
             ('but', 4264),
             ('it', 13884),
             ('no', 2262),
             ('pictures', 104),
             ('conversations', 52),
             ('in', 9454),
             ('w

In [17]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

2727

In [0]:
import numpy as np

In [0]:
sequences = np.array(sequences)

In [20]:
sequences

array([[  11,   12,  298, ...,  672,    5,   20],
       [  12,  298,    3, ...,    5,   20,  813],
       [ 298,    3,  102, ...,   20,  813,   66],
       ...,
       [   5,   42,  412, ..., 2727, 1455,  812],
       [  42,  412,   21, ..., 1455,  812, 1456],
       [ 412,   21,   22, ...,  812, 1456,    1]])

In [0]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding, Dropout

In [0]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(256, return_sequences=True))
    model.add(Dropout(0.1))
    model.add(LSTM(256))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

In [0]:
from keras.utils import to_categorical

In [24]:
sequences

array([[  11,   12,  298, ...,  672,    5,   20],
       [  12,  298,    3, ...,    5,   20,  813],
       [ 298,    3,  102, ...,   20,  813,   66],
       ...,
       [   5,   42,  412, ..., 2727, 1455,  812],
       [  42,  412,   21, ..., 1455,  812, 1456],
       [ 412,   21,   22, ...,  812, 1456,    1]])

In [25]:
# First 49 words
sequences[:,:-1]

array([[  11,   12,  298, ...,   59,  672,    5],
       [  12,  298,    3, ...,  672,    5,   20],
       [ 298,    3,  102, ...,    5,   20,  813],
       ...,
       [   5,   42,  412, ...,    1, 2727, 1455],
       [  42,  412,   21, ..., 2727, 1455,  812],
       [ 412,   21,   22, ..., 1455,  812, 1456]])

In [26]:
# last Word
sequences[:,-1]

array([  20,  813,   66, ...,  812, 1456,    1])

In [0]:
X = sequences[:,:-1]

In [0]:
y = sequences[:,-1]

In [0]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [30]:
seq_len = X.shape[1]
seq_len

25

In [31]:
# define model
model = create_model(vocabulary_size+1, seq_len)

W0727 12:37:33.468214 140362715903872 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0727 12:37:33.515830 140362715903872 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0727 12:37:33.522735 140362715903872 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0727 12:37:34.038597 140362715903872 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0727 12:37:34.053612 

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 25, 25)            68200     
_________________________________________________________________
lstm_1 (LSTM)                (None, 25, 256)           288768    
_________________________________________________________________
dropout_1 (Dropout)          (None, 25, 256)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 256)               525312    
_________________________________________________________________
dense_1 (Dense)              (None, 150)               38550     
_________________________________________________________________
dense_2 (Dense)              (None, 2728)              411928    
Total params: 1,332,758
Trainable params: 1,332,758
Non-trainable params: 0
_________________________________________________________________


In [0]:
from pickle import dump,load

In [33]:
# fit model
model.fit(X, y, batch_size=128, epochs=200,verbose=1)

W0727 12:37:34.701425 140362715903872 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/200
26905/26905 [==============================] - 34s 1ms/step - loss: 6.2897 - acc: 0.0573
Epoch 2/200
26905/26905 [==============================] - 25s 925us/step - loss: 5.9028 - acc: 0.0618
Epoch 3/200
26905/26905 [==============================] - 25s 930us/step - loss: 5.6746 - acc: 0.0690
Epoch 4/200
26905/26905 [==============================] - 25s 926us/step - loss: 5.5179 - acc: 0.0709
Epoch 5/200
26905/26905 [==============================] - 25s 928us/step - loss: 5.4125 - acc: 0.0757
Epoch 6/200
26905/26905 [==============================] - 25s 928us/step - loss: 5.3283 - acc: 0.0797
Epoch 7/200
26905/26905 [==============================] - 25s 926us/step - loss: 5.2581 - acc: 0.0844
Epoch 8/200
26905/26905 [==============================] - 25s 925us/step - loss: 5.1916 - acc: 0.0879
Epoch 9/200
26905/26905 [==============================] - 25s 926us/step - loss: 5.1320 - acc: 0.0921
Epoch 10/200
26905/26905 [==============================] - 25s 928us/step 

In [0]:
# save the model to file
model.save('epochBIG.h5')
# save the tokenizer
dump(tokenizer, open('epochBIG', 'wb'))

In [0]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [0]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    print("Seed text is: ", input_text)
    print('\n')
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

In [37]:
text_sequences[0]

['alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'bank',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'do',
 'once',
 'or',
 'twice',
 'she',
 'had']

In [0]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [0]:
random_seed_text = text_sequences[random_pick]

In [40]:
random_seed_text

['does',
 'nt',
 'look',
 'like',
 'one',
 'but',
 'it',
 'is',
 'i',
 'quite',
 'agree',
 'with',
 'you',
 'said',
 'the',
 'duchess',
 'and',
 'the',
 'moral',
 'of',
 'that',
 'isbe',
 'what',
 'you',
 'would',
 'seem']

In [0]:
seed_text = ' '.join(random_seed_text)

In [42]:
seed_text

'does nt look like one but it is i quite agree with you said the duchess and the moral of that isbe what you would seem'

In [44]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=200)

Seed text is:  does nt look like one but it is i quite agree with you said the duchess and the moral of that isbe what you would seem




'to beor as you d like it was too moreas the baby and got on he began the games in the hedge in another offended was off in alices head and she set to alice like she had rather forgotten she pictured to go dry then the cupboards as i was talking of such a long of a little key and here us thought the fight and himself by her eyes but she was talking as wet the dormouse turned on off and it would not help whether she walked off the right size for herself and twelve like the earth then the blades what marked and on one and twice less him to herself as she ran for her sister prizes she did to be a little hot indeed getting off and then one of one you know now what she was nt a bit afraid to be to get at the glass hair as if he had been a week there was three gardeners at first to eat at the whiting where the time alice had made the fan and concluded the banquet but she tucked her the part call us and behind it and they thinking said'